### 4.1 Exercise on Functions
#### Task 1: Unit Conversion Program

In [ ]:
def convert_length(value, direction):
    """
    Converts between meters and feet.

    Parameters:
        value (float): The numerical value to convert.
        direction (str): 'mtf' for meters to feet, 'ftm' for feet to meters.

    Returns:
        float: The converted value.
    """
    if direction == 'mtf':
        return value * 3.28084
    elif direction == 'ftm':
        return value / 3.28084
    else:
        raise ValueError("Invalid direction. Use 'mtf' or 'ftm'.")


def convert_weight(value, direction):
    """
    Converts between kilograms and pounds.

    Parameters:
        value (float): The numerical value to convert.
        direction (str): 'ktl' for kg to lbs, 'ltk' for lbs to kg.

    Returns:
        float: The converted value.
    """
    if direction == 'ktl':
        return value * 2.20462
    elif direction == 'ltk':
        return value / 2.20462
    else:
        raise ValueError("Invalid direction. Use 'ktl' or 'ltk'.")


def convert_volume(value, direction):
    """
    Converts between liters and gallons.

    Parameters:
        value (float): The numerical value to convert.
        direction (str): 'ltg' for liters to gallons, 'gtl' for gallons to liters.

    Returns:
        float: The converted value.
    """
    if direction == 'ltg':
        return value * 0.264172
    elif direction == 'gtl':
        return value / 0.264172
    else:
        raise ValueError("Invalid direction. Use 'ltg' or 'gtl'.")


def unit_converter():
    """
    Main function to drive the unit conversion program.
    Prompts the user to select a conversion type, input a value,
    and displays the converted result. Handles invalid input gracefully.

    Returns:
        float: The converted result, or None if input was invalid.
    """
    print("Unit Converter")
    print("Choose a conversion type:")
    print("1. Length  (meters <-> feet)")
    print("2. Weight  (kg <-> lbs)")
    print("3. Volume  (liters <-> gallons)")

    try:
        category = input("Enter category (1/2/3): ").strip()

        if category == '1':
            print("  a) Meters to Feet")
            print("  b) Feet to Meters")
            sub = input("Enter option (a/b): ").strip().lower()
            direction = 'mtf' if sub == 'a' else 'ftm'
            unit_in = 'meters' if sub == 'a' else 'feet'
            unit_out = 'feet' if sub == 'a' else 'meters'
            value = float(input(f"Enter value in {unit_in}: "))
            result = convert_length(value, direction)

        elif category == '2':
            print("  a) Kilograms to Pounds")
            print("  b) Pounds to Kilograms")
            sub = input("Enter option (a/b): ").strip().lower()
            direction = 'ktl' if sub == 'a' else 'ltk'
            unit_in = 'kg' if sub == 'a' else 'lbs'
            unit_out = 'lbs' if sub == 'a' else 'kg'
            value = float(input(f"Enter value in {unit_in}: "))
            result = convert_weight(value, direction)

        elif category == '3':
            print("  a) Liters to Gallons")
            print("  b) Gallons to Liters")
            sub = input("Enter option (a/b): ").strip().lower()
            direction = 'ltg' if sub == 'a' else 'gtl'
            unit_in = 'liters' if sub == 'a' else 'gallons'
            unit_out = 'gallons' if sub == 'a' else 'liters'
            value = float(input(f"Enter value in {unit_in}: "))
            result = convert_volume(value, direction)

        else:
            print("Invalid category selected.")
            return None

        print(f"\nResult: {value} {unit_in} = {result:.4f} {unit_out}")
        return result

    except ValueError as e:
        print(f"Error: Invalid input - {e}")
        return None



unit_converter()

Unit Converter
Choose a conversion type:
1. Length  (meters <-> feet)
2. Weight  (kg <-> lbs)
3. Volume  (liters <-> gallons)
  a) Kilograms to Pounds
  b) Pounds to Kilograms

Result: 333.0 lbs = 151.0464 kg


151.04643884206803

#### Task 2: Mathematical Operations on a List of Numbers

In [3]:
def compute_sum(numbers):
    """
    Computes the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of all elements in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    total = 0
    for n in numbers:
        total += n
    return total


def compute_average(numbers):
    """
    Computes the average (mean) of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of all elements in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return compute_sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The maximum value in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    max_val = numbers[0]
    for n in numbers:
        if n > max_val:
            max_val = n
    return max_val


def compute_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The minimum value in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    min_val = numbers[0]
    for n in numbers:
        if n < min_val:
            min_val = n
    return min_val


def math_operations_program():
    """
    Interactive program that performs mathematical operations on user-supplied numbers.
    Supports sum, average, maximum, and minimum. Handles invalid input and empty lists.

    Returns:
        float or None: The result of the selected operation, or None on error.
    """
    print("Math Operations Program")
    print("=" * 30)
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = input("Enter choice (1/2/3/4): ").strip()
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.strip().split()]

        ops = {'1': compute_sum, '2': compute_average,
               '3': compute_maximum, '4': compute_minimum}
        op_names = {'1': 'Sum', '2': 'Average', '3': 'Maximum', '4': 'Minimum'}

        if choice not in ops:
            print("Invalid choice.")
            return None

        result = ops[choice](numbers)
        print(f"\n{op_names[choice]}: {result}")
        return result

    except ValueError as e:
        print(f"Error: {e}")
        return None


# Empty list error handling
try:
    compute_sum([])
except ValueError as e:
    print(f"\nEmpty list error caught: {e}")


math_operations_program()


Empty list error caught: List is empty.
Math Operations Program
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum

Sum: 45.0


45.0

---
### 4.2 Exercise on List Manipulation

In [4]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    """Returns every other element starting from the first."""
    return lst[::2]

print("1. Extract every other:", extract_every_other([1, 2, 3, 4, 5, 6]))


# 2. Slice a Sublist
def get_sublist(lst, start, end):
    """Returns a sublist from index start to end (inclusive)."""
    return lst[start:end + 1]

print("2. Sublist [2:4]       :", get_sublist([1, 2, 3, 4, 5, 6], 2, 4))


# 3. Reverse a List Using Slicing
def reverse_list(lst):
    """Returns a reversed copy of the list using slicing."""
    return lst[::-1]

print("3. Reversed list       :", reverse_list([1, 2, 3, 4, 5]))


# 4. Remove the First and Last Elements
def remove_first_last(lst):
    """Returns the list without its first and last elements."""
    return lst[1:-1]

print("4. Remove first & last :", remove_first_last([1, 2, 3, 4, 5]))


# 5. Get the First n Elements
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

print("5. First 3 elements    :", get_first_n([1, 2, 3, 4, 5], 3))


# 6. Extract Elements from the End
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

print("6. Last 2 elements     :", get_last_n([1, 2, 3, 4, 5], 2))


# 7. Extract Elements in Reverse Order (every second, starting from second-to-last)
def reverse_skip(lst):
    """Returns every second element starting from the second-to-last, moving backward."""
    return lst[-2::-2]

print("7. Reverse skip        :", reverse_skip([1, 2, 3, 4, 5, 6]))

1. Extract every other: [1, 3, 5]
2. Sublist [2:4]       : [3, 4, 5]
3. Reversed list       : [5, 4, 3, 2, 1]
4. Remove first & last : [2, 3, 4]
5. First 3 elements    : [1, 2, 3]
6. Last 2 elements     : [4, 5]
7. Reverse skip        : [5, 3, 1]


---
### 4.3 Exercise on Nested List

In [5]:
# 1. Flatten a Nested List
def flatten(lst):
    """Flattens a one-level nested list into a single list."""
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

print("1. Flatten            :", flatten([[1, 2], [3, 4], [5]]))


# 2. Access Nested Element by Indices
def access_nested_element(lst, indices):
    """Extracts an element from a nested list given a list of indices."""
    element = lst
    for idx in indices:
        element = element[idx]
    return element

nested = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("2. Access [1][2]      :", access_nested_element(nested, [1, 2]))


# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    """Recursively sums all numeric elements in a nested list of arbitrary depth."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print("3. Sum nested         :", sum_nested([[1, 2], [3, [4, 5]], 6]))


# 4. Remove Specific Element from Nested List
def remove_element(lst, elem):
    """Removes all occurrences of elem from a one-level nested list."""
    return [[x for x in sublist if x != elem] for sublist in lst]

print("4. Remove 2           :", remove_element([[1, 2], [3, 2], [4, 5]], 2))


# 5. Find Maximum Element in a Nested List
def find_max(lst):
    """Finds the maximum element in a nested list of arbitrary depth."""
    max_val = None
    for item in lst:
        if isinstance(item, list):
            candidate = find_max(item)
        else:
            candidate = item
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val

print("5. Max nested         :", find_max([[1, 2], [3, [4, 5]], 6]))


# 6. Count Occurrences in a Nested List
def count_occurrences(lst, elem):
    """Counts how many times elem appears in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print("6. Count 2 in list    :", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))


# 7. Deep Flatten (any depth)
def deep_flatten(lst):
    """Recursively flattens a list of any nesting depth into a single list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print("7. Deep flatten       :", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))


# 8. Nested List Average
def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print("8. Average nested     :", average_nested([[1, 2], [3, 4], [5, 6]]))

1. Flatten            : [1, 2, 3, 4, 5]
2. Access [1][2]      : 6
3. Sum nested         : 21
4. Remove 2           : [[1], [3], [4, 5]]
5. Max nested         : 6
6. Count 2 in list    : 3
7. Deep flatten       : [1, 2, 3, 4, 5, 6, 7, 8]
8. Average nested     : 3.5


---
## Section 10: NumPy Exercises
---

In [6]:
import numpy as np
import time

### 10.1 Basic Vector and Matrix Operations
#### Problem 1: Array Creation

In [7]:
# 1. Empty array of size 2x2
empty_2x2 = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_2x2)

# 2. All-ones array of size 4x2
ones_4x2 = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_4x2)

# 3. Array filled with a specific fill value
filled_array = np.full((3, 3), fill_value=7)
print("\n3. Array filled with 7 (3x3):\n", filled_array)

# 4. Zeros array with same shape as an existing array
existing = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like = np.zeros_like(existing)
print("\n4. zeros_like(existing):\n", zeros_like)

# 5. Ones array with same shape as an existing array
ones_like = np.ones_like(existing)
print("\n5. ones_like(existing):\n", ones_like)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\n6. List to numpy array:", np_array, "| dtype:", np_array.dtype)

1. Empty 2x2 array:
 [[2.16886195e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. zeros_like(existing):
 [[0 0 0]
 [0 0 0]]

5. ones_like(existing):
 [[1 1 1]
 [1 1 1]]

6. List to numpy array: [1 2 3 4] | dtype: int64


#### Problem 2: Array Manipulation – Numerical Ranges and Array Indexing

In [9]:
# 1. Array with values from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. Range 10 to 49:\n", arr_10_49)

# 2. 3x3 matrix with values 0 to 8
matrix_0_8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0-8):\n", matrix_0_8)

# 3. 3x3 identity matrix
identity_3 = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_3)

# 4. Random array of size 30, find mean
rand_30 = np.random.random(30)
print(f"\n4. Random array (size 30) mean: {rand_30.mean():.6f}")

# 5. 10x10 random array, find min and max
rand_10x10 = np.random.random((10, 10))
print(f"\n5. 10x10 random array -> min: {rand_10x10.min():.6f}, max: {rand_10x10.max():.6f}")

# 6. Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1  # index 4 = 5th element
print("\n6. Zero array with 5th element = 1:\n", zero_arr)

# 7. Reverse an array
arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr_to_reverse[::-1]
print("\n7. Reversed array:", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
bordered = np.zeros((6, 6))
bordered[0, :] = 1
bordered[-1, :] = 1
bordered[:, 0] = 1
bordered[:, -1] = 1
print("\n8. Border array (6x6):\n", bordered)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard 8x8:\n", checkerboard)

1. Range 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30) mean: 0.462250

5. 10x10 random array -> min: 0.022333, max: 0.983184

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border array (6x6):
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

9. Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Problem 3: Array Operations

In [10]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add
print("1. x + y:\n", x + y)

# 2. Subtract
print("\n2. x - y:\n", x - y)

# 3. Multiply by scalar
scalar = 3
print(f"\n3. x * {scalar}:\n", x * scalar)

# 4. Square of each element
print("\n4. x ** 2:\n", x ** 2)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5a. dot(v, w) :", dot_vw)
print("5b. dot(x, v) :", dot_xv)
print("5c. dot(x, y):\n", dot_xy)

# 6. Concatenate x and y along rows (axis=0) and v and w along columns
concat_rows = np.vstack((x, y))           # row-wise stack
concat_cols = np.concatenate((v, w))      # v and w are 1D → horizontal concat
print("\n6a. vstack(x, y):\n", concat_rows)
print("6b. concatenate(v, w):", concat_cols)

# 7. Concatenate x and v (demonstrate the error)
print("\n7. Trying np.concatenate(x, v) along axis=0:")
try:
    result = np.concatenate((x, v), axis=0)
except ValueError as e:
    print(f"   Error: {e}")
    print("   Explanation: x has shape", x.shape, "and v has shape", v.shape,
          "\n   They have different numbers of dimensions (2D vs 1D),",
          "so concatenation along axis=0 fails.",
          "\n   Fix: reshape v to (1,2) first.")
    # Fixed version
    result_fixed = np.concatenate((x, v.reshape(1, 2)), axis=0)
    print("   Fixed result (v reshaped to (1,2)):\n  ", result_fixed)

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x ** 2:
 [[ 1  4]
 [ 9 25]]

5a. dot(v, w) : 219
5b. dot(x, v) : [29 77]
5c. dot(x, y):
 [[19 22]
 [50 58]]

6a. vstack(x, y):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. concatenate(v, w): [ 9 10 11 12]

7. Trying np.concatenate(x, v) along axis=0:
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Explanation: x has shape (2, 2) and v has shape (2,) 
   They have different numbers of dimensions (2D vs 1D), so concatenation along axis=0 fails. 
   Fix: reshape v to (1,2) first.
   Fixed result (v reshaped to (1,2)):
   [[ 1  2]
 [ 3  5]
 [ 9 10]]


#### Problem 4: Matrix Operations

In [11]:
A = np.array([[3, 4], [7, 8]], dtype=float)
B = np.array([[5, 3], [2, 1]], dtype=float)

# 1. Prove A . A_inv = I
A_inv = np.linalg.inv(A)
product_AinvA = np.dot(A, A_inv)
print("1. A · A⁻¹ (should be Identity):\n", np.round(product_AinvA, 6))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA?", np.allclose(AB, BA))  # Should be False

# 3. Prove (AB)^T = B^T * A^T
AB_T   = AB.T
BT_AT  = np.dot(B.T, A.T)
print("\n3. (AB)ᵀ:\n", AB_T)
print("   BᵀAᵀ:\n", BT_AT)
print("   (AB)ᵀ == BᵀAᵀ?", np.allclose(AB_T, BT_AT))  # Should be True

print("\n" + "="*50)

# Solve system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

A_sys = np.array([[2, -3,  1],
                  [1, -1,  2],
                  [3,  1, -1]], dtype=float)
B_vec = np.array([-1, -3, 9], dtype=float)

# Method 1: Using np.linalg.inv
A_sys_inv = np.linalg.inv(A_sys)
X_inv_method = np.dot(A_sys_inv, B_vec)
print("\nSolve: AX = B")
print("Coefficient matrix A:\n", A_sys)
print("Constants vector B:", B_vec)
print("\nSolution using Inverse Method (X = A⁻¹ · B):")
print(f"  x = {X_inv_method[0]:.6f}")
print(f"  y = {X_inv_method[1]:.6f}")
print(f"  z = {X_inv_method[2]:.6f}")

# Method 2: Using np.linalg.solve
X_solve = np.linalg.solve(A_sys, B_vec)
print("\nSolution using np.linalg.solve:")
print(f"  x = {X_solve[0]:.6f}")
print(f"  y = {X_solve[1]:.6f}")
print(f"  z = {X_solve[2]:.6f}")

# Verify
print("\nVerification (A · X should equal B):", np.round(np.dot(A_sys, X_solve), 6))

1. A · A⁻¹ (should be Identity):
 [[1. 0.]
 [0. 1.]]

2. AB:
 [[23. 13.]
 [51. 29.]]
   BA:
 [[36. 44.]
 [13. 16.]]
   AB == BA? False

3. (AB)ᵀ:
 [[23. 51.]
 [13. 29.]]
   BᵀAᵀ:
 [[23. 51.]
 [13. 29.]]
   (AB)ᵀ == BᵀAᵀ? True


Solve: AX = B
Coefficient matrix A:
 [[ 2. -3.  1.]
 [ 1. -1.  2.]
 [ 3.  1. -1.]]
Constants vector B: [-1. -3.  9.]

Solution using Inverse Method (X = A⁻¹ · B):
  x = 2.000000
  y = 1.000000
  z = -2.000000

Solution using np.linalg.solve:
  x = 2.000000
  y = 1.000000
  z = -2.000000

Verification (A · X should equal B): [-1. -3.  9.]


---
### 10.2 Experiment: How Fast is NumPy?

In [ ]:
SIZE = 1_000_000

# Pre-generate data
list_a = [float(i) for i in range(SIZE)]
list_b = [float(i) * 2 for i in range(SIZE)]
np_a = np.array(list_a)
np_b = np.array(list_b)

print("="*60)
print("EXPERIMENT: NumPy vs Python Lists")
print(f"Array size: {SIZE:,}")
print("="*60)

# 1. Element-wise Addition
# Python list
t0 = time.time()
result_list = [list_a[i] + list_b[i] for i in range(SIZE)]
t_list_add = time.time() - t0

# NumPy
t0 = time.time()
result_np = np_a + np_b
t_np_add = time.time() - t0

print(f"\n1. Element-wise Addition")
print(f"   Python List : {t_list_add:.6f} s")
print(f"   NumPy       : {t_np_add:.6f} s")
print(f"   Speedup     : {t_list_add/t_np_add:.1f}x")

# 2. Element-wise Multiplication
t0 = time.time()
result_list = [list_a[i] * list_b[i] for i in range(SIZE)]
t_list_mul = time.time() - t0

t0 = time.time()
result_np = np_a * np_b
t_np_mul = time.time() - t0

print(f"\n2. Element-wise Multiplication")
print(f"   Python List : {t_list_mul:.6f} s")
print(f"   NumPy       : {t_np_mul:.6f} s")
print(f"   Speedup     : {t_list_mul/t_np_mul:.1f}x")

# 3. Dot Product
t0 = time.time()
dot_list = sum(list_a[i] * list_b[i] for i in range(SIZE))
t_list_dot = time.time() - t0

t0 = time.time()
dot_np = np.dot(np_a, np_b)
t_np_dot = time.time() - t0

print(f"\n3. Dot Product")
print(f"   Python List : {t_list_dot:.6f} s")
print(f"   NumPy       : {t_np_dot:.6f} s")
print(f"   Speedup     : {t_list_dot/t_np_dot:.1f}x")

# 4. Matrix Multiplication (1000 x 1000)
MAT_SIZE = 1000
mat_a_list = [[float(i * MAT_SIZE + j) for j in range(MAT_SIZE)] for i in range(MAT_SIZE)]
mat_b_list = [[float(i * MAT_SIZE + j) for j in range(MAT_SIZE)] for i in range(MAT_SIZE)]
mat_a_np = np.array(mat_a_list)
mat_b_np = np.array(mat_b_list)

# Python list matrix multiplication
t0 = time.time()
result_mat_list = [[sum(mat_a_list[i][k] * mat_b_list[k][j]
                        for k in range(MAT_SIZE))
                    for j in range(MAT_SIZE)]
                   for i in range(MAT_SIZE)]
t_list_mat = time.time() - t0

# NumPy
t0 = time.time()
result_mat_np = np.dot(mat_a_np, mat_b_np)
t_np_mat = time.time() - t0

print(f"\n4. Matrix Multiplication ({MAT_SIZE}x{MAT_SIZE})")
print(f"   Python List : {t_list_mat:.4f} s")
print(f"   NumPy       : {t_np_mat:.6f} s")
print(f"   Speedup     : {t_list_mat/t_np_mat:.1f}x")

print("\n" + "="*60)
print("Conclusion: NumPy is dramatically faster due to vectorized")
print("C-level operations, avoiding Python's interpreter overhead.")
print("="*60)

EXPERIMENT: NumPy vs Python Lists
Array size: 1,000,000

1. Element-wise Addition
   Python List : 0.108873 s
   NumPy       : 0.004992 s
   Speedup     : 21.8x

2. Element-wise Multiplication
   Python List : 0.127491 s
   NumPy       : 0.006348 s
   Speedup     : 20.1x

3. Dot Product
   Python List : 0.088771 s
   NumPy       : 0.001509 s
   Speedup     : 58.8x
